#!/usr/bin/env python3
"""Generate the one-to-one atomic acceptance/test specification."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def case(
    identifier: str,
    criterion: str,
    attribute: str,
    level: str,
    purpose: str,
    preconditions: str,
    input_data: str,
    steps: str,
    expected: str,
    postconditions: str,
    test_code: str,
) -> dict:
    return {
        "id": identifier,
        "atomic_acceptance_criterion": criterion,
        "quality_attribute": attribute,
        "test_level": level,
        "test_purpose": purpose,
        "preconditions": preconditions,
        "input_data": input_data,
        "operation_steps": steps,
        "expected_result": expected,
        "postconditions": postconditions,
        "test_code": test_code,
        "evidence_file": f"reports/evidence/hdr_{level}.json",
    }


CASES = [
    case("ST-CI-APPLE-SDK", "build 与 Checks 任务必须在 macOS 26/Xcode 26/SDK 26 上验证 HDR 编译；Release 必须在 macOS 15 runner 的 macOS 15 SDK 上编译，产物最低可运行版本固定为 15.0，并固定 Qt 6.11.2。", "精益完整性", "static", "验证 CI 根因修复、Release SDK 降级和本机 macOS 15 兼容契约不会因 runner 或工具链漂移而回归。", "workflow 文件、CMake 配置和 Release 脚本可读。", "runs-on、xcodebuild、xcrun、Qt 版本、CMAKE_OSX_DEPLOYMENT_TARGET 和产物校验断言。", "分别检查 build/test、release 和 release-compatibility 的 runner、Xcode/SDK 约束、Qt 版本、macOS 15 deployment target 以及 Release 产物 minOS 校验。", "build/test 使用 macos-26 且 Xcode/SDK 主版本至少 26；Release/compatibility 使用 macos-15 且 SDK 主版本恰为 15；全部配置固定 deployment target 15.0，Qt 固定 6.11.2，Release 脚本和 compatibility job 检查 Mach-O SDK/minOS 和 LSMinimumSystemVersion。", "不启动 Actions，不修改远程状态。", "tests/hdr_quality_static.py"),
    case("ST-CI-BUILD-PARALLELISM", "Checks 的 CMake 构建必须使用有界并行度，避免在 GitHub Actions 作业时间窗内因无界编译并行而超时；build 和 release 也必须保持同一界限。", "时间行为", "static", "验证本轮 CI 超时修复不会因并行参数回退而复发。", "三个 workflow 文件可读。", "三个 workflow 的 CMake build 命令。", "检查 test、build、release 的构建命令，拒绝 Checks 中无界的 --parallel。", "Checks、build、release 均使用 cmake --build build --parallel 2，且 Checks 不含无界并行命令。", "不启动 Actions，不修改远程状态。", "tests/hdr_quality_static.py"),
    case("ST-HDR-RAW-CONTENT-UTI", "RAW 必须按文件内容 UTI 而非扩展名分类。", "功能正确性", "static", "验证 RAW 分类入口。", "源码可读。", "RAW UTI 判定实现。", "检查 CGImageSourceGetType 与 public.camera-raw-image conformance，确认 RAW 分支不读取 suffix。", "内容 UTI 唯一决定 isRaw。", "不修改源码。", "tests/hdr_quality_static.py"),
    case("ST-HDR-RAW-CIRAWFILTER", "传统 RAW 主路径必须使用两个独立 CIRAWFilter 图，并完整保留相机默认 BaselineExposure。", "精益完整性", "static", "验证 NEF 等传感器 RAW 的原生解码图与 HDR 策略。", "Objective-C++ 源码可读。", "RAW decode 分支。", "检查两次 filterWithImageURL、extendedDynamicRangeAmount=0/1、无 baselineExposure 赋值与 NativeHDRImage 发布。", "惰性 SDR/EDR 图不共享可变 filter 状态，且不人为损坏相机曝光配方。", "不触发实际解码。", "tests/hdr_quality_static.py"),
    case("ST-HDR-RAW-PREVIEW-FALLBACK", "普通 RAW 预览只能用于失败回退；仅含已配对 HDR gain map 的全尺寸处理预览可作为显式主表示。", "功能正确性", "static", "区分低质量兜底预览与 Quick Look 风格 Adaptive-HDR 处理预览。", "源码可读。", "RAW fallback 与 processed-gain-map 控制流。", "检查 fallback 顺序、gain-map 门控、usesProcessedRawPreview/usedRawPreview 与错误路径。", "普通预览不冒充 RAW HDR；DNG 已配对处理预览可审计。", "不修改源码。", "tests/hdr_quality_static.py"),
    case("ST-HDR-NONRAW-METADATA", "非 RAW 必须解析 gain map、headroom、色彩空间和传输函数。", "功能正确性", "static", "验证 HDR 元数据覆盖。", "macOS SDK 符号可编译。", "Apple/ISO gain map 与 PQ/HLG 代码。", "检查两类 auxiliary data、CG/CI headroom、PQ/HLG 判定。", "所有关键 HDR 元数据均有解析路径。", "不解码文件。", "tests/hdr_quality_static.py"),
    case("ST-HDR-NONRAW-RECONSTRUCTION", "非 RAW HDR 必须通过 Image I/O HDR 请求与 CI expand 重建。", "功能正确性", "static", "验证 gain-map/ISO HDR 重建链。", "源码可读。", "非 RAW decode 分支。", "检查 DecodeToHDR、kCIImageExpandToHDR、方向与候选判定。", "HDR graph 不经普通 SDR 加载路径。", "不修改源码。", "tests/hdr_quality_static.py"),
    case("ST-HDR-NONRAW-NONVOLATILE-DECODE", "Gain-map JPEG 的 SDR/HDR 源必须在初始化时进入非易失解码缓存，且只在源图缓存后执行视口裁剪。", "功能正确性", "static", "防止延迟 gain-map 求值在缩放或拖动 ROI 中产生黑带和旧 tile。", "Core Image 非 RAW 解码与 renderer 源码可读。", "HDR/SDR CIImage options、source-space intermediate 与 viewport transform。", "检查两个 recipe 均设置 kCIImageCacheImmediately=YES，并验证 imageByInsertingIntermediate 位于 imageForTexture 之前。", "源图和 gain map 在局部 render 前已稳定解码；视口几何不成为源缓存键。", "不执行实际解码。", "tests/hdr_quality_static.py"),
    case("ST-HDR-FLOAT-INTERMEDIATE", "HDR 主路径必须保持 half-float CI 图，RGBA8 只能用于回退。", "功能正确性", "static", "验证禁止提前量化不变量。", "源码可读。", "CIContext、NativeHDRImage、loader。", "检查 RGBAh context、CIImage retain、跨 loader 句柄和具名 SDR fallback helper。", "主图保持浮点，QImage 仅为 fallback。", "不分配图像。", "tests/hdr_quality_static.py"),
    case("ST-HDR-COLORSYNC", "HDR 工作/输出空间必须由 ColorSync 建立扩展线性 Display P3。", "功能正确性", "static", "验证色彩管理链。", "ColorSync/Core Image 源码可读。", "色彩空间与 CI context 设置。", "检查 Display P3 profile、extended linearization、working/output space。", "源到显示的 CI/ColorSync 变换完整。", "不改变系统 profile。", "tests/hdr_quality_static.py"),
    case("ST-HDR-METAL-EDR-SURFACE", "最终 surface 必须是 Metal RGBA16Float 且请求 EDR。", "功能正确性", "static", "验证 WindowServer 前的输出契约。", "源码与构建文件可读。", "CAMetalLayer/CIContext 配置。", "检查 Metal context、RGBA16Float、wantsEDR 与 QuartzCore 链接。", "输出 layer 符合 EDR 精度契约。", "不创建窗口。", "tests/hdr_quality_static.py"),
    case("ST-HDR-DISPLAY-ADAPTATION", "每次绘制必须读取窗口所在屏幕的当前/潜在 headroom。", "功能正确性", "static", "验证动态显示适配。", "renderer 源码可读。", "NSScreen 查询与测试 override。", "检查 window.screen、current/potential EDR API，以及区分全显示能力与仅 current 的确定性 override。", "显示能力不是启动时常量，且可独立控制 bootstrap 前置条件。", "不改变真实 headroom。", "tests/hdr_quality_static.py"),
    case("ST-HDR-EDR-BOOTSTRAP", "当前 headroom 仍为 1、但潜在 headroom>1 时，renderer 必须用潜在能力启动首个 EDR 帧。", "功能正确性", "static", "防止等待已有 EDR 内容才输出 EDR 的循环依赖。", "NSScreen 与 renderer 源码可读。", "current/potential/content 三种 headroom。", "检查纯策略 helper、rendering headroom、bootstrapping 诊断和 target 计算链。", "潜在 EDR 显示器可从 current=1 启动 HDR；潜在值=1 时仍保持 SDR。", "不改变系统 headroom。", "tests/hdr_quality_static.py"),
    case("ST-HDR-TONE-MAPPING", "非 RAW HDR 必须按内容/显示 headroom 色调映射。", "功能正确性", "static", "验证 HDR 与 SDR 输出兼容。", "macOS 15 SDK 可用。", "CIToneMapHeadroom 和 CALayer 配置。", "检查 source/target headroom 参数及 automatic layer tone map。", "系统 tone mapper 接收正确的两端 headroom。", "不渲染像素。", "tests/hdr_quality_static.py"),
    case("ST-HDR-DNG-PROCESSED-GAINMAP", "DNG 必须优先组合全尺寸 CIRAWFilter.previewImage 与配对 gain map，并按目标 headroom 动态重建。", "功能正确性", "static", "保留 Quick Look 接近的相机处理细节与真实 HDR。", "macOS 15 Core Image API 可用。", "DNG processed preview、auxiliary gain map 与 renderer。", "检查 previewImage、auxiliaryHDRGainMap、applyingGainMap:headroom 与 retained gain map。", "DNG 不使用被人为提亮的通用 RAW 配方；显示 headroom 直接驱动 gain-map 重建。", "不改变相机 metadata。", "tests/hdr_quality_static.py"),
    case("ST-HDR-DNG-GAINMAP-ROI", "半分辨率 DNG gain map 的已应用图不得插入会固化首个 ROI 的中间缓存。", "功能正确性", "static", "防止 4032×3024 ROI 被固化到 8064×6048 extent 后只剩左上象限。", "renderer 源码可读。", "processed RAW 与传统 RAW 两类端点。", "检查 processed RAW 直接 retain 完整源、传统 RAW 仍使用 managed intermediate，所有 viewport transform 在提交时执行。", "处理预览四象限始终来自完整源；其他 RAW 仍可缓存。", "不渲染窗口。", "tests/hdr_quality_static.py"),
    case("ST-HDR-GEOMETRY", "HDR layer 必须复用缩放、滚动、旋转与镜像几何。", "功能正确性", "static", "验证原生层不脱离 Qt 交互。", "view/renderer 源码可读。", "四角映射和 CI 仿射矩阵。", "检查 viewportTransform、四角与 Metal destination affine。", "HDR 图与逻辑源尺寸使用同一变换。", "不改变视图。", "tests/hdr_quality_static.py"),
    case("ST-HDR-STAGED-FIRST-FRAME", "最终几何和首个 drawable 呈现前不得移除 SDR 占位或显示 Metal layer。", "功能正确性", "static", "防止空 layer、JPEG 黑块与旧几何首帧。", "view/renderer 源码可读。", "几何稳定 gate、SDR proxy、layer opacity 和 presented handler。", "检查稳定回调才 arm、proxy 常驻到 presented、Metal 从 opacity 0 切到 1。", "未呈现阶段始终有正确占位，且不会暴露空 drawable。", "不创建窗口。", "tests/hdr_quality_static.py"),
    case("ST-HDR-OFFSCREEN-PREPARATION", "HDR 最终 headroom 首求值与代表性 4× zoom ROI 必须在任何 Metal 像素可见前由 Core Image 管理的 float intermediate 完成。", "时间行为", "static", "防止 RAW 首求值或首次 zoom ROI 编码占用交互窗口并泄露部分 tile。", "renderer 源码可读。", "最终 HDR endpoint、4× ROI 与串行预热 command buffer。", "检查 cacheIntermediates、finalDisplayImage(1.0)、interactionWarmCorners、renderQueue 预热，确认无 partial ramp 预热且不调用 imageWithMTLTexture。", "首次可见帧与交互复用已编译的完整 float workset；应用自有 render-target 从不反向作为 CI 输入。", "缓存只随图像替换销毁。", "tests/hdr_quality_static.py"),
    case("ST-HDR-FIRST-VISIBLE-FINAL", "应用只能提交最终 headroom 首帧，并在 SDR proxy 或上一张 HDR drawable 上以 compositor opacity 平滑揭示。", "功能正确性", "static", "移除 partial-headroom 闪变，同时避免最终 EDR surface 单帧跳入。", "view/renderer 源码可读。", "首帧状态机、presented handler、最终 endpoint 与 presentation container。", "检查生产 render 固定 progress=1、final reveal gate、proxy handoff、上一 drawable 保留、手动 pixel ramp 已删除，并检查 opacity CABasicAnimation。", "任何可见 Metal 首帧都是 prepared、geometry-complete 的最终 HDR；可见混合由 Core Animation 连续过渡。", "不创建窗口。", "tests/hdr_quality_static.py"),
    case("ST-HDR-FOCUS-PRESENTATION-TRANSITION", "HDR presentation 必须随窗口/应用活动状态可逆淡入淡出，且淡出终点前不得关闭 EDR。", "功能正确性", "static", "保证失焦平滑回到 SDR proxy、重新聚焦平滑恢复且快速反转无跳变。", "view/renderer 源码可读。", "WindowActivate/Deactivate、applicationState、presentationLayer opacity 与 EDR flag。", "检查活动状态传播、SDR proxy 预提交、从 presentationLayer 当前值反转、450 ms opacity 动画及淡出完成后关闭 EDR。", "焦点转换连续可逆；任一可见 HDR fade-out 帧仍为 EDR，终点 opacity=0/EDR=false。", "不改变真实窗口焦点。", "tests/hdr_quality_static.py"),
    case("ST-HDR-GEOMETRY-LIFECYCLE", "首帧前几何变化可以失效未呈现 generation；首帧呈现且端点预热后，缩放、拖动或 resize 必须复用源端点并保持 HDR 可见。", "功能正确性", "static", "防止 DNG 局部空白、拖动残影以及交互亮度回落。", "view/renderer 源码可读。", "viewport size、四角、34ms debounce、generation、prepared 状态和 layer opacity。", "检查完整几何比较、首帧前 invalidate、呈现后 reuseVisibleHDR、源空间 cache 与 autoresizingMask。", "未呈现帧由 proxy 隔离；已呈现 HDR 在几何变化期间不清缓存、不降 opacity、不切回 SDR。", "不触发真实输入。", "tests/hdr_quality_static.py"),
    case("ST-HDR-DISPLAYLINK-LATEST-ONLY", "首帧及超出持久缓存预算的回退 drawable 必须全部来自 CAMetalDisplayLink；pending 只保留最新几何，并允许最多两帧重叠。", "时间行为", "static", "消除单帧 GPU-completion→主线程门限、无节拍 drawable 突发、idle pause/wake 竞态、旧 drawable-pool 停顿与几何积压。", "macOS 14 SDK 与 renderer 源码可读。", "首帧、超预算图像的 zoom/pan、viewport resize、DisplayLink callback、targetTimestamp deadline 与两帧在途计数。", "检查 drawableSize 在 Qt/AppKit 请求线程更新且尺寸变化后重绑 DisplayLink、唯一 DisplayLink drawable 来源、交互 keep-alive 内不暂停、latest overwrite、in-flight≤2、completion 原子释放、off-main CI encode、普通 present（禁止 atTime）、deadline 观测与 ordered commit。", "首帧和回退请求由显示时钟提交；keep-alive 到期前 callback 持续提交；resize 后 callback 继续；CPU 编码、GPU 执行和 scanout 可安全重叠；停止后收敛到最新几何。", "不启动显示循环。", "tests/hdr_quality_static.py"),
    case("ST-HDR-PERSISTENT-COMPOSITOR-FAST-PATH", "预算内 HDR 图像完成首帧后必须物化为有界 half-float 持久 surface；拖动只更新 Core Animation 仿射几何，不再申请 drawable 或重画隐藏 Qt backing store。", "时间行为", "static", "解除窗口合成 present latency 与三 drawable 池对交互吞吐的上限。", "Core Image、Core Animation 与 renderer 源码可读。", "完整 HDR endpoint、512 MiB 预算、pan/zoom geometry、120Hz probe。", "检查后台 kCIFormatRGBAh createCGImage(deferred:NO)、尺寸/字节上限、affineTransform、Metal pause/hide、NoViewportUpdate 以及 compositor/Metal 计数遥测。", "预算内交互只提交轻量 layer transaction；超预算图像保留 CAMetalDisplayLink 回退；测试可以区分 compositor 更新和 Metal present。", "不启动显示循环。", "tests/hdr_quality_static.py"),
    case("ST-HDR-PRESENTATION-TELEMETRY", "平均/P99/最大呈现时延与吞吐必须由 addPresentedHandler 的真实呈现事件计算，而非 command-buffer 提交时间推断。", "可测试性", "static", "建立可机器审计的 WindowServer 前最后观察点。", "renderer 源码可读。", "presentedTime、请求时间、generation 与 final-headroom flag。", "检查 addPresentedHandler、单调时钟 fallback、原子计数/间隔/request-to-present 以及 FOVELLE_PRESENT JSON。", "系统测试可重建每个真实呈现帧的时间与 endpoint 属性。", "默认诊断开关关闭时不输出逐帧日志。", "tests/hdr_quality_static.py"),
    case("ST-HDR-UI-REQUEST-COALESCING", "paint、双轴 scrollbar 和过渡 timer 必须只发布 dirty request，并在下一事件循环合并成一次 renderer 调用。", "时间行为", "static", "避免同一拖动事件同步触发多次完整 CI/Metal 提交。", "视图源码可读。", "paint+水平+垂直+timer 更新。", "检查 0ms single-shot request timer、唯一 hdrRenderer->render 调用点和交互时延遥测。", "主线程每轮最多提交一个最新状态，悬浮按钮事件保持可响应。", "不触发交互。", "tests/hdr_quality_static.py"),
    case("ST-HDR-NAV-NATIVE-COMPOSITOR", "覆盖真实 HDR 像素的导航 artwork 必须作为原生 layer tree 内的 shape-only sibling 合成，并由启用 group opacity 的单一按钮父层逐 tick 使用实时 paintOpacity；SDR 路径保留透明 QWidget。", "功能正确性", "static", "消除跨 surface 有色矩形，并保证底板与符号以同一曲线出现/消失。", "主窗口与 Objective-C++ renderer 源码可读。", "按钮圆角底、chevron、父层 group opacity、HDR/SDR surface 选择及坐标系。", "检查 CAShapeLayer/CGPath、native sibling、allowsGroupOpacity、禁用隐式动画、坐标映射、HDR 时 button->hide，并确认子层保持 opacity=1。", "HDR artwork 与命中区对齐；底板和符号先成组再由实时 paintOpacity 统一淡化；SDR 行为不回归。", "不创建窗口。", "tests/hdr_quality_static.py"),
    case("ST-HDR-NAV-CACHED-SAMPLING", "悬浮按钮对比度采样必须读取一次性有界代理，禁止 viewport()->grab，并按 QGraphicsPixmapItem 的设备无关几何映射 Retina 像素。", "时间行为", "static", "避免 hover 为采样同步触发两次 HDR paint/Metal render，并避免高 DPI 下把右侧按钮误映射到图像左半侧。", "主窗口/视图源码可读。", "postLoad 缓存、QGraphicsPixmapItem 几何与 hover 点。", "检查≤384px sample、3×3 pixelColor 读取、无 viewport grab、mapFromScene/boundingRect 设备无关映射。", "hover 工作量与 48MP/RAW 渲染成本解耦，且 Retina 与非 Retina 使用同一图像内容坐标。", "不采集屏幕。", "tests/hdr_quality_static.py"),
    case("ST-HDR-OBSERVABILITY", "运行态必须非侵入式输出解码、渲染、headroom、过渡、帧调度、背景色与 viewport/图像像素裁剪遥测。", "可测试性", "static", "验证机器可观测接口与桌面无关的截图测量。", "源码可读。", "FOVELLE_HDR compact JSON。", "检查 JSON 日志、decode/render timing、content/layer/display headroom、transition、DisplayLink/off-main/generation、主题 RGB、image corners 及 viewport global origin/size/DPR 字段。", "系统测试可从 stderr 恢复完整状态、证明调度收敛并把背景/结构截图指标限制到被测区域。", "默认未设置环境变量时不输出。", "tests/hdr_quality_static.py"),
    case("ST-HDR-RAW-STABLE-ENDPOINTS", "交互 RAW renderer 必须使用两个不可互相变异的图、启用 CIContext intermediate cache，并显式缓存源空间 SDR/HDR 端点。", "功能正确性", "static", "防止定时相关的 RAW tile 丢失或部分空白。", "RAW decoder 与 renderer 源码可读。", "独立 CIRAWFilter、CI context options 与 source intermediates。", "检查两个 filter 变量、kCIContextCacheIntermediates=YES、两次 imageByInsertingIntermediate:YES。", "重复渲染和变换不会依赖上一次可变 filter 状态，源端点可按需稳定复用。", "不执行 RAW 解码。", "tests/hdr_quality_static.py"),
    case("ST-HDR-RAW-CONTENT-HEADROOM", "RAW 未报告 content headroom 时必须从浮点 HDR 峰值解析，并把实际目标而非显示潜力写入 CIImage/CAMetalLayer 内容标签。", "功能正确性", "static", "防止把约 1.8× 内容错误标成 16× 后被系统强烈压暗。", "macOS HDR API 源码可读。", "CIRAWFilter HDR graph、CIAreaMaximum、CIImage/CALayer headroom。", "检查浮点峰值约减、resolvedHDRContentHeadroom、imageBySettingContentHeadroom 和 layer contentsHeadroom=target。", "内容标签表达像素范围；显示能力只作为 target 上限，不冒充内容 metadata。", "不更改显示器 headroom。", "tests/hdr_quality_static.py"),
    case("ST-HDR-THEME-BACKGROUND", "Qt painter 与 Metal drawable 必须使用同一显式主题背景色，并经 sRGB→扩展线性 P3 色彩管理合成。", "功能正确性", "static", "消除约两秒后 Metal reveal 导致的背景变浅和主题切换失效。", "主窗口、视图与 renderer 源码可读。", "Light #969696、Dark #212121。", "检查共享 viewportBackgroundColor、renderer setter、sRGB source tag、opaque composite，并确认未使用 NSColor.windowBackgroundColor。", "Metal reveal 前后背景颜色合同不变；设置更新可立即重绘新主题。", "不修改持久化主题。", "tests/hdr_quality_static.py"),
    case("ST-HDR-INTERACTION-NO-REACTIVATION", "HDR 打开激活完成后，任何缩放、平移或 resize 均不得重置渐亮时钟、进度或切回 SDR proxy。", "功能正确性", "static", "移除交互时先变暗再变亮的全场景特性。", "视图状态机源码可读。", "activationCompleted、presented/prepared reuse policy 与 stageHDRGeometry。", "检查 canReuseHDRPresentation、stage 内无 clock/progress reset、完成标记与复用时 fallback=false。", "平缓变亮仅绑定新图像打开；交互只改变几何。", "不触发真实输入。", "tests/hdr_quality_static.py"),
    case("ST-CONTEXT-MENU-POINTER-OWNERSHIP", "macOS 右键菜单必须在 Qt 收到真实 rightMouseUp 后，以不携带 pointer event 的原生 positioning API 打开；禁止合成或直接派发 down/up。", "功能正确性", "static", "防止菜单 tracking 吞掉 release 后 Qt 拖动状态与 AppKit 事件流失配。", "应用、主窗口与 Cocoa bridge 源码可读。", "Qt 6.8+ release trigger 与旧版 Qt fallback。", "检查 ContextMenuTrigger::Release、真实 mouseButtons gate、popUpMenuPositioningItem，并确认不存在 mouseEventWithType/rightMouseUp direct dispatch。", "Qt 在菜单开始 tracking 前已处理真实 release，且菜单启动不再需要第二套 pointer event。", "不触发输入。", "tests/hdr_quality_static.py"),
    case("ST-HDR-VERSION-0.1.4", "所有发布版本来源必须一致为 0.1.4。", "精益完整性", "static", "验证版本合同。", "CMake、qmake、plist 和测试源码可读。", "四类版本来源。", "逐一比较 0.1.4。", "静态版本来源一致。", "不修改构建缓存。", "tests/hdr_quality_static.py"),
    case("UT-HDR-TRANSITION", "HDR 内容过渡函数必须有界且单调。", "功能正确性", "unit", "确定性验证 smoothstep。", "无需物理显示器。", "[-1,2] 及 0..1 百分点。", "调用 easedHDRTransition 并比较端点与相邻值。", "输出在 [0,1]、端点正确且不下降。", "无全局状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testTransitionCurveIsBoundedAndMonotonic"),
    case("UT-HDR-FIRST-VISIBLE-FINAL", "partial-headroom drawable 无论进度多接近 1 都不得成为首个可见 Metal 帧。", "功能正确性", "unit", "确定性验证最终 endpoint reveal gate。", "纯 helper 可调用。", "geometry=true，progress=-1/0/0.5/0.998/0.999/1/2。", "调用 isFinalHDRFrameReadyForReveal。", "<0.999 全 false，≥0.999 全 true。", "无时钟或显示状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testFinalFrameRevealRejectsPartialHeadroom"),
    case("UT-HDR-HEADROOM-CLAMP", "目标 headroom 不得超过内容与显示可用值。", "功能正确性", "unit", "验证 headroom 不变量。", "纯 helper 可调用。", "content/display 4/6、8/3、unknown/3。", "计算完整与半程过渡。", "完整值分别为 4、3、3，半程在 1 与 4 之间。", "无显示状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testHDRHeadroomIsClampedToContentAndDisplay"),
    case("UT-HDR-SDR-FALLBACK", "显示 headroom=1 时任何 HDR 内容目标都必须为 1。", "功能正确性", "unit", "确定性验证 SDR 自动兼容。", "纯 helper 可调用。", "content=4.9473、display=1、三种 progress。", "计算 effectiveHDRHeadroom。", "三次均严格等于 1。", "无显示状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testSDRDisplayForcesUnitHeadroom"),
    case("UT-HDR-EDR-BOOTSTRAP", "rendering headroom 必须在 current=1/potential>1 时启动 EDR，并在 current>1 后跟随动态 current。", "功能正确性", "unit", "确定性验证 EDR bootstrap 策略。", "纯 helper 可调用。", "(1,1,5)、(1,16,4.9473)、(1,4,unknown)、(3.5,16,5)。", "调用 displayHeadroomForRendering 并逐项比较。", "分别得到 1、4.9473、4、3.5。", "无显示状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testDisplayHeadroomBootstrapsFromPotentialCapability"),
    case("UT-HDR-FIRST-VISIBLE-GEOMETRY", "即使 headroom 已最终化，drawable 几何不匹配时仍不得揭示。", "功能正确性", "unit", "确定性验证首帧几何 gate。", "纯 helper 可调用。", "progress=1，geometry=false/true。", "调用 isFinalHDRFrameReadyForReveal。", "几何不匹配返回 false，匹配返回 true。", "无 UI 或显示状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testFinalFrameRevealRequiresMatchedGeometry"),
    case("UT-HDR-GEOMETRY-EQUIVALENCE", "Metal 几何稳定判定必须比较 viewport size 与全部四角，并只容忍规定的浮点误差。", "功能正确性", "unit", "验证 debounce 输入合同而不依赖真实窗口。", "纯 helper 可调用。", "相同几何、0.005/0.02 像素差、不同 viewport、不同角点数。", "调用 hdrViewportGeometryEquivalent。", "相同与 0.005 差返回 true；其余返回 false。", "无 UI 状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testHDRViewportGeometryEquivalenceUsesCompleteContract"),
    case("UT-HDR-SCROLLBAR-CENTER", "Cocoa AsNeeded 滚动条出现或消失时，缩放前后可用 viewport 中心对应的归一化图像坐标变化不得超过 0.5%，且前置条件失败时测试必须安全退出。", "功能正确性", "unit", "验证不同 macOS/Qt viewport 与滚动条布局下的缩放中心不跳变，并防止失败断言继续执行导致崩溃。", "可见 Cocoa 窗口、可读 viewport 尺寸和临时 PNG。", "按当前 viewport 的 90% 生成图片，1.0 倍缩放后执行一次 1.25 倍缩放。", "等待初始无滚动条、等待两轴滚动条出现，分别在可用 viewport 中心采样归一化图像坐标，并等待 expensive scaling 稳定。", "两次滚动条状态符合预期；布局切换和高质量缩放前后的坐标差均≤0.005；任一前置条件失败都清理窗口并返回。", "关闭窗口并恢复 quitOnLastWindowClosed；临时文件由 QTemporaryDir 清理。", "tests/tst_qviewtests.cpp::GraphicsViewTests::testZoomAcrossScrollbarThresholdKeepsViewportCenterStable"),
    case("UT-HDR-CONTENT-HEADROOM", "未知或无效的 RAW content headroom 必须优先解析为有效浮点峰值，且结果至少为 1。", "功能正确性", "unit", "确定性验证内容范围解析，不依赖显示器能力。", "纯 helper 可调用。", "reported/measured=(4,1.8)、(0,1.8321)、(0,0.7)、(-1,-2)。", "调用 resolvedHDRContentHeadroom。", "结果依次为 4、1.8321、1、1。", "无图像或显示状态变化。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testRawContentHeadroomUsesMeasuredPeakWhenUnknown"),
    case("UT-HDR-PRESENTATION-REUSE", "仅当 HDR 首帧已呈现且源端点已准备时，几何交互才允许复用可见 HDR。", "功能正确性", "unit", "穷举验证交互不重启的 gate。", "纯 helper 可调用。", "presented/prepared 的四种布尔组合。", "逐项调用 canReuseHDRPresentation。", "只有 true/true 返回 true。", "不改变 renderer generation。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testPreparedHDRPresentationCanBeReusedAcrossGeometry"),
    case("UT-HDR-THEME-BACKGROUND", "共享主题背景解析必须严格返回 Light #969696 和 Dark #212121。", "功能正确性", "unit", "验证 Qt 与 Metal 可共享的确定性色值。", "无需窗口。", "Light、Dark 两枚 Theme 枚举。", "调用 viewportBackgroundColor 并比较 QColor。", "两项与发布颜色合同逐位一致。", "不改变 palette 或设置。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testViewportBackgroundColorsMatchTheme"),
    case("UT-HDR-RENDERER-CONTRACT", "renderer 必须报告 float、ColorSync、扩展线性 P3 与 EDR。", "可测试性", "unit", "通过诊断结构验证 surface。", "Cocoa 与 Metal 可用。", "320×200 QWidget。", "创建 renderer 并读取 diagnostics。", "所有精度/色彩/EDR flag 为 true，图像尚未 active。", "销毁临时 layer。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testRendererUsesFloatEDRColorManagedSurface"),
    case("UT-HDR-NAV-SAMPLING-LATENCY", "10,000 次悬浮亮度采样必须在 250ms 内完成。", "时间行为", "unit", "量化缓存采样不会阻塞 hover。", "已加载 split fixture。", "viewport 中心点重复 10,000 次。", "调用 sampleDisplayedImageBrightness 并计时。", "全部有效且总耗时≤250ms。", "窗口关闭且 renderer 状态不变。", "tests/tst_qviewtests.cpp::WindowBehaviorTests::testNavigationBrightnessSamplingIsBounded"),
    case("UT-HDR-NAV-TRANSPARENT-FADE", "按钮半透明渲染的四角 alpha 必须为 0，且完整 artwork 的每个像素统一乘以 paintOpacity。", "功能正确性", "unit", "像素级验证无矩形底面且底板/符号速度一致。", "MainWindow 可构造。", "两个按钮在 paintOpacity=1 与 0.5 下的 ARGB。", "检查属性/effect/animation，渲染两帧并逐像素比较 alpha。", "四角透明、每个非零像素的半透明 alpha 等于完整 alpha 的一半、graphicsEffect=null。", "释放临时 image/window。", "tests/tst_qviewtests.cpp::WindowBehaviorTests::testNavigationButtonUsesTransparentPaintOnlyFade"),
    case("UT-HDR-SDR-CLASSIFICATION", "普通 SDR 图不得被错误提升到 HDR 主路径。", "功能正确性", "unit", "验证 HDR 分类负例。", "临时目录可写。", "32×32 sRGB PNG。", "经 Image I/O 解码并检查结果。", "QImage 有效、HDR handle 为空、decodedToHDR=false。", "删除临时文件。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testSDRImageStaysOnSDRPath"),
    case("UT-HDR-FORMAT-COVERAGE", "目标 macOS 必须声明所需 RAW 与非 RAW 格式。", "精益完整性", "unit", "验证格式覆盖。", "使用目标机 Image I/O。", "dng/nef/cr3/arw/raf/jpeg/heif/heic/avif。", "逐个查询 supportsAdditionalImageFormat。", "全部格式返回支持。", "释放类型列表。", "tests/tst_qviewtests.cpp::HDRPolicyTests::testRequiredHDRFormatsAreAdvertised"),
    case("UT-HDR-VERSION", "运行时应用版本必须为 0.1.4。", "功能正确性", "unit", "验证编译定义传到运行时。", "测试应用已初始化。", "applicationVersion。", "读取并比较字符串。", "严格等于 0.1.4。", "不改变应用元数据。", "tests/tst_qviewtests.cpp::FeatureTests::testApplicationVersionIsCurrent"),
    case("IT-HDR-GAINMAP-JPEG", "提供的 JPEG 必须产生全分辨率 adaptive HDR 句柄。", "功能正确性", "integration", "验证真实 gain-map JPEG。", "样例存在且 macOS 14+。", "IMG_1735.JPG，fallback 2048px。", "编译测试调用生产 decoder 并检查 UTI、gain map、headroom、尺寸。", "HDR handle/full resolution 保留，headroom>1，只有 SDR fallback≤2048。", "释放 CI graph。", "tests/tst_qviewtests.cpp::HDRSampleTests::testGainMapJPEGCreatesNativeHDRGraph"),
    case("IT-HDR-GAINMAP-JPEG-PEAK", "提供的 gain-map JPEG HDR 图必须包含超过 SDR white 的浮点值。", "功能正确性", "integration", "用像素数据证明非 RAW HDR 不是仅有 metadata flag。", "样例存在且 Image I/O 可展开 gain map。", "同一 JPEG 的 SDR/HDR CI graph。", "以 CIAreaMaximum 约减两图并比较 RGB 峰值。", "HDR 峰值>1.05 且至少比 SDR 高 0.05。", "释放 probe context 和 CI graph。", "tests/tst_qviewtests.cpp::HDRSampleTests::testGainMapJPEGHDRContainsAboveSDRValues"),
    case("IT-HDR-RAW-DNG", "提供的 DNG 必须产生全尺寸处理预览＋gain map HDR 句柄。", "功能正确性", "integration", "验证真实 DNG 的 Quick Look 风格公开表示。", "样例存在且 Apple RAW/gain-map API 支持。", "IMG_8625.DNG，fallback 2048px。", "生产 decoder 检查 RAW、processed preview、gain map、16-bit、尺寸。", "sourceKind=camera-raw-processed-gain-map、full resolution 且 fallback 有界。", "释放 CI graphs。", "tests/tst_qviewtests.cpp::HDRSampleTests::testDNGCreatesProcessedGainMapHDRGraph"),
    case("IT-HDR-RAW-DNG-PEAK", "提供的 DNG gain-map 图必须包含超过 SDR white 的真实浮点值。", "功能正确性", "integration", "用像素证明 DNG HDR。", "样例可解码。", "处理预览 SDR/HDR endpoints。", "CIAreaMaximum 比较 RGB 峰值。", "SDR≤1.01、HDR>1.05 且至少高 0.05。", "释放 probe context。", "tests/tst_qviewtests.cpp::HDRSampleTests::testDNGProcessedGainMapContainsAboveSDRValues"),
    case("IT-HDR-RAW-DNG-HEADROOM-TAG", "DNG gain-map metadata headroom 必须不低于 half-float 实测峰值且差值≤0.05。", "功能正确性", "integration", "验证内容 metadata 未被显示潜力或量化峰值替代。", "样例可解码。", "metadata 与 CIAreaMaximum。", "解码并比较。", "metadata>1.5、metadata≥measured-0.001、差≤0.05。", "释放 graphs。", "tests/tst_qviewtests.cpp::HDRSampleTests::testDNGGainMapHeadroomMatchesMetadataContract"),
    case("IT-HDR-RAW-DNG-REPEATABILITY", "DNG processed SDR/HDR endpoints 连续两次求值必须稳定。", "功能正确性", "integration", "捕获时序依赖。", "样例已解码。", "同一 handle 两次 probe。", "比较 SDR/HDR maximum。", "均 valid 且差≤0.001。", "不修改 graph。", "tests/tst_qviewtests.cpp::HDRSampleTests::testDNGProcessedGraphRepeatedFloatProbeIsStable"),
    case("IT-HDR-RAW-PLAIN-DNG", "sample1.dng 必须走不可变双 CIRAWFilter 传感器 RAW HDR 路径，而非误判为处理预览。", "功能正确性", "integration", "验证本轮 plain DNG 打开样例的真实解码合同。", "sample1.dng 存在且 Apple RAW 支持。", "sample1.dng + 2048px fallback。", "生产 decoder 检查 flags/source/precision/full size 并比较浮点 SDR/HDR 峰值。", "camera-raw、usesRawEDR=true、processedPreview=false、HDR>SDR+0.05。", "释放 RAW graphs。", "tests/tst_qviewtests.cpp::HDRSampleTests::testPlainDNGCreatesNativeRawEDRGraph"),
    case("IT-HDR-RAW-NEF", "提供的 NEF 必须产生保留相机默认的双 CIRAWFilter EDR 句柄。", "功能正确性", "integration", "验证 Nikon RAW 主路径。", "sample1.nef 存在且 Apple RAW 支持。", "NEF + 2048px fallback。", "检查 flags/source/precision/full size 并 probe 峰值。", "camera-raw、usesRawEDR=true、preview=false、HDR>SDR+0.05。", "释放 RAW graphs。", "tests/tst_qviewtests.cpp::HDRSampleTests::testNEFCreatesNativeRawEDRGraph"),
    case("IT-HDR-RAW-NEF-REPEATABILITY", "NEF SDR/HDR endpoints 连续两次求值必须稳定。", "功能正确性", "integration", "排除可变 filter 状态。", "NEF 已解码。", "两次全图 probe。", "比较两个 endpoint。", "均 valid 且差≤0.001。", "不改变 filter。", "tests/tst_qviewtests.cpp::HDRSampleTests::testNEFRawRepeatedFloatProbeIsStable"),
    case("IT-HDR-DNG-QUICKLOOK-DETAIL", "DNG 处理预览与系统 Quick Look 缩略图的边缘结构相似度必须≥0.994，RGB MAE≤3。", "功能正确性", "integration", "量化相机处理细节接近 Quick Look。", "qlmanage、Swift/Core Image、Pillow 可用。", "同一 DNG 的 1024px Quick Look 与 CIRAWFilter.previewImage。", "生成两 PNG，比较 FIND_EDGES cosine 与 RGB MAE，并验证 preview/gain-map 尺寸。", "cosine≥0.994、MAE≤3、preview=8064×6048、gain=4032×3024。", "证据 PNG 保留在 reports/evidence/quicklook_quality。", "tests/hdr_quality_integration.py"),
    case("IT-RELEASE-MACOS15-ARTIFACT", "构建出的 Release bundle 主可执行文件和 Info.plist 必须声明 macOS 15.0，且嵌入依赖不得要求高于 macOS 15。", "功能正确性", "integration", "在编译后、签名发布前验证本机可安装运行的最低系统版本合同。", "已生成 build/Fovelle.app，otool、PlistBuddy 和 file 可用。", "Fovelle.app 内全部 Mach-O、Contents/Info.plist。", "解析每个 Mach-O 的 LC_BUILD_VERSION minos，读取主可执行文件 SDK 家族和 LSMinimumSystemVersion，并检查嵌入依赖的 minOS 不高于 15.0。", "主可执行文件 minOS=15.0，Info.plist=15.0，所有嵌入依赖 minOS≤15.0。", "不签名、不修改应用 bundle。", "tests/macos15_release_contract.py::validate_app"),
    case("SYS-RELEASE-MACOS15-INSTALL-SMOKE", "Release bundle 必须复制/部署 Qt 依赖、压缩解压后仍保持 macOS 15 兼容合同，并能在本机 macOS 15 启动。", "功能正确性", "system", "验证用户实际安装路径而非只验证构建目录。", "本机 macOS 15、已构建 Fovelle.app、macdeployqt、ditto 和 Cocoa 会话可用。", "隔离临时目录中的 app bundle、macOS15 zip 和启动进程。", "复制 app，运行 macdeployqt，创建并解压 zip，重新检查 Mach-O/Info.plist，启动解压后的可执行文件并在确定时间窗后终止。", "Qt 部署、zip 往返、macOS 15 兼容合同和启动均通过；测试不依赖签名/公证凭据。", "删除临时安装目录，保留启动日志和结构化证据。", "tests/hdr_quality_system.py::install_extract_and_launch"),
    case("SYS-HDR-GAINMAP-JPEG-EDR", "真实窗口中的 gain-map JPEG 必须达到 EDR target>1。", "功能正确性", "system", "端到端验证非 RAW HDR。", "XDR Mac、Cocoa app 和样例可用。", "JPEG 启动 3 次。", "打开窗口、采集 7s FOVELLE_HDR telemetry。", "每次识别 adaptive HDR/gain map 且 target>1.1。", "终止测试进程，保存日志。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-RAW-DNG-EDR", "真实窗口中的 DNG 必须走全尺寸处理预览＋gain map EDR 图。", "功能正确性", "system", "端到端验证接近 Quick Look 配方的 DNG HDR。", "XDR Mac、Cocoa app 和样例可用。", "DNG 启动 3 次。", "打开窗口并采集 RAW renderer telemetry。", "isRaw、processed preview、gain map、16-bit 为真，sourceKind=camera-raw-processed-gain-map，target>1.1。", "终止测试进程，保存日志。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-NO-PREMATURE-BLACK-FRAME", "首个 Metal 帧实际呈现前必须由 SDR proxy 覆盖且 layer opacity=0。", "功能正确性", "system", "端到端验证 JPEG 黑块与 DNG 未完成 RAW 首帧修复。", "真实 Cocoa Window 与 telemetry 可用。", "JPEG/DNG 共 6 次真实启动记录。", "检查所有 presented=false 记录的 fallback/opacity，并检查 opacity>0 的呈现、完整 prepared geometry 与 drawable。", "空或未完成求值的 drawable 永不裸露；Metal 只在完整预热帧呈现后显示。", "关闭测试窗口。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-RAW-CONTENT-HEADROOM", "DNG 完成激活后的渲染目标必须等于实测 RAW content headroom 与显示可用 headroom 的较小值；支持 CALayer 内容标签的系统还必须写入同值。", "功能正确性", "system", "端到端验证内容范围与显示能力没有混淆。", "XDR Mac、DNG 和 content/display telemetry 可用。", "三次 DNG 完成 transition 的 telemetry。", "筛选 progress≥0.999，比较 content、target、display potential/rendering；若 runtime 支持 contentsHeadroom，再比较 layer 实值。", "content>1.5；target≈min(content,rendering)；content 不被潜在 16× 能力替代；可用时 layer≈target。", "关闭测试窗口并保留 API 支持状态和数值。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-FINAL-LAYOUT-BEFORE-METAL", "任何 Metal 提交都必须使用稳定的完整 viewport 几何和匹配的 drawable。", "功能正确性", "system", "端到端验证 DNG 完整→局部空白→完整故障修复。", "真实 Cocoa Window、DNG 与 screencapture 可用。", "三次 DNG telemetry，以及 clean-start 后 3.6～6.2s 的 10 帧截图。", "验证 layout_ready、geometry_pending=false、drawable match；在图像 crop 内计算各帧边缘向量与最终帧余弦相似度。", "提交只发生在稳定 geometry 且 drawable 完整匹配；10 帧结构相似度均≥0.90。", "保留截图、哈希和结构指标并关闭窗口。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-RAW-NO-BLANK-REGION", "DNG 从首个可见 Metal 帧到稳定 HDR 的十个时间点均不得丢失有结构的图像 tile。", "功能正确性", "system", "以屏幕像素捕获间歇性白色/空白区域。", "DNG clean-start、screencapture 和 Pillow 可用。", "3.6～6.2s 十帧的图像区域与最终参考帧。", "把图像分为 8×6 tiles，比较 FIND_EDGES 能量，标记参考有结构但当前低于 35% 的 tile。", "最终参考至少 20 个结构 tile；每一帧 missing tile count=0。", "保留十帧、哈希、crop 和逐 tile 能量。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-FLOAT-COLORMANAGED-EDR-SURFACE", "端到端 surface 必须持续报告 RGBA16Float/ColorSync/EDR。", "功能正确性", "system", "验证实际窗口 layer 配置。", "两种 HDR 样例可渲染。", "全部真实运行 telemetry。", "聚合每帧配置 flag。", "所有记录均为 float、扩展 P3、ColorSync、wantsEDR。", "销毁窗口 layer。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-FIRST-VISIBLE-FINAL", "JPEG、processed DNG、plain DNG 与 NEF 的首个可见 Metal 帧必须已预热、几何完整且为最终 headroom；不得显示应用生成的中间亮度帧。", "功能正确性", "system", "端到端消除打开时闪一下，并保留系统级一次性 EDR 适配。", "真实 Cocoa/Metal 窗口、四类样例与逐呈现 telemetry 可用。", "IMG_1735.JPG、IMG_8625.DNG、sample1.dng、sample1.nef。", "逐次启动，定位第一个 opacity>0/presented 记录，并核对所有 FOVELLE_PRESENT endpoint。", "每个 firstVisibleFinal=true、progress=1、prepared/matched=true；所有 presented finalHeadroom=true；任何 opacity>0 记录都无 partial progress。", "关闭窗口并保留逐帧呈现日志。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-WINDOWSERVER-HEADROOM", "EDR layer 必须与 WindowServer 协商出可用 headroom>1。", "功能正确性", "system", "验证物理 XDR 输出而非 SDR bitmap。", "内建 XDR 显示器可用。", "真实运行的 current/potential/rendering/target headroom。", "读取每帧 NSScreen telemetry 并比较能力与渲染上限。", "potential>1、rendering>1，target 不超过 rendering；系统可随后提升 current。", "系统自行恢复亮度策略。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-EDR-BOOTSTRAP", "clean-start current headroom=1 时 JPEG 与 DNG 均必须在潜在 EDR 显示器上达到 target>1。", "功能正确性", "system", "端到端验证无其他 HDR 客户端时仍有真实 HDR。", "XDR 显示器 potential>1，current-only override 可用。", "JPEG/DNG + FOVELLE_TEST_DISPLAY_CURRENT_HEADROOM=1。", "分别打开真实窗口并采集 bootstrap、rendering 和 target telemetry。", "两格式 bootstrapping_edr=true、rendering>1、target>1.1 且最终 prepared geometry active。", "清除子进程 override。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-FORCED-SDR-COMPATIBILITY", "强制显示 headroom=1 时真实 renderer target 必须保持 1。", "功能正确性", "system", "端到端验证 SDR 自动兼容。", "测试 override 可用。", "JPEG + FOVELLE_TEST_DISPLAY_HEADROOM=1。", "打开真实窗口并采集 telemetry。", "override=true 且所有 current/target 均为 1。", "清除子进程环境变量。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-JPEG-BAND-FREE", "JPEG 稳态和缩放/拖动序列中不得出现贯穿图像的大块纯黑竖带或拖动后残影。", "功能正确性", "system", "以屏幕像素证据验证非易失源解码和 managed-intermediate 修复。", "允许 screencapture，Pillow 可读 PNG。", "JPEG 稳态及确定性交互期间的屏幕截图。", "采集多帧，计算中间 86% 高度内近黑像素占比≥80%的最大连续列；比较交互稳定后的最后两帧边缘结构。", "每帧最大连续黑列≤10；最后两帧边缘余弦相似度≥0.995，证明没有旧 tile/残影。", "保留截图、哈希、黑列指标和结构相似度。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-INTERACTION-GEOMETRY", "HDR 完成激活后的缩放/拖动必须复用同一 prepared generation，保持 layer 可见，并只以新四角提交完整 drawable。", "功能正确性", "system", "端到端验证拖动残影和交互中错误 proxy 切换修复。", "真实 Cocoa Window 与确定性交互 driver 可用。", "JPEG 的 zoom×4 与 48 步双轴 scrollbar 移动。", "采集 geometry-reused、render、finished telemetry。", "reuse 期间 presented/prepared=true、fallback=false、opacity=1、generation/reset 不变；render 无 pending geometry，交互后 HDR 完整。", "driver 自动停止且窗口关闭。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-INTERACTION-NO-REACTIVATION", "JPEG、processed DNG 与 NEF 完成首次 HDR 揭示后，任何缩放或移动均不得回落 headroom、重显 SDR fallback 或重新触发亮度提升。", "功能正确性", "system", "端到端验证亮度提升只属于图片打开。", "三类 HDR 已在真实 EDR 窗口完成激活。", "三格式各 zoom×4、48 步 pan 与 settled telemetry。", "逐格式检查 geometry-reused/settled 的 activation/final/fallback/opacity。", "全部 progress=1、firstVisibleFinal=true、fallback=false、opacity=1。", "关闭测试窗口。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-DISPLAYLINK-LATEST-ONLY", "JPEG、processed DNG 与 NEF 的首帧必须由 DisplayLink 有序提交，随后切换 persistent compositor；停止后必须收敛到最新请求。", "时间行为", "system", "端到端验证首帧 latest-only 调度与交互零 drawable 快路径。", "真实 Cocoa/Metal/Core Animation 窗口和交互 driver 可用。", "三格式连续 zoom/pan telemetry。", "聚合 opening DisplayLink callback、persistent readiness、compositor geometry、Metal interaction submission、frames-in-flight、generation 与异常日志。", "三格式 persistent ready、compositor update≥48、interaction Metal submission=0、frames-in-flight≤2、settled requested=submitted 且无 CAMetalLayerInvalidOperation。", "关闭窗口并保存调度计数。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-INTERACTION-RESPONSIVENESS", "放大后的 JPEG、processed DNG 与 NEF 拖动必须满足 AppKit 事件循环平均/P99/最大时延和吞吐量阈值。", "时间行为", "system", "量化拖动卡顿和悬浮控件响应风险。", "真实窗口、确定性 12ms pan driver 可用。", "三格式各一次 zoom×4 与 48 步双轴 pan。", "读取 zoom 同步耗时与相邻 callback 间隔，计算 average/P99/max/steps-per-second。", "三格式 zoom≤30ms、average≤25ms、P99≤45ms、max≤60ms、吞吐≥40 steps/s，步骤0…47无丢失。", "driver 停止并保存原始时间戳。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-PRESENTATION-RESPONSIVENESS", "HDR 拖动必须在 persistent compositor 快路径达到至少 120 geometry updates/s，并且不重建交互 Metal drawable。", "时间行为", "system", "避免把 input callback 数或 Metal commit 数冒充持久图层的显示能力。", "真实 Core Animation 窗口、三格式交互及无 verbose logging 的专用 probe 可用。", "JPEG、processed DNG、NEF 的48步窗口和独立 JPEG 8ms probe。", "核对 opening present 均为 final-headroom、三格式 persistent ready/compositor count；独立解析 FOVELLE_HDR_120HZ 的 elapsed/rate/compositor/Metal 计数。", "48步≤400ms、rate≥120/s、compositor≥48、last geometry≤1ms、interaction Metal present=0；三格式 regular interaction 均走 persistent surface。", "关闭窗口并保留专用 probe 记录；VSync/hitch 另由 Instruments 证据验证。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-NEF-ZOOM-NO-GHOST", "NEF 缩放序列不得显示旧代际残影、黑带或结构缺失。", "功能正确性", "system", "以调度代际和真实屏幕像素验证 NEF 残影修复。", "sample1.nef、screencapture、Pillow 和真实 Cocoa 窗口可用。", "NEF zoom×4/pan 期间一帧及停止后三帧。", "所有帧比较 8×6 tile 边缘结构和黑带；同构图的后三帧比较 edge cosine；核对 settled generation。", "四帧 missing tile=0、黑带≤10列；后三帧 edge cosine≥0.995；最终 requested=submitted 且无在途帧。", "保留截图、哈希、crop 与逐 tile 能量。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-NAV-NATIVE-COMPOSITOR", "放大图像覆盖按钮区域时，HDR 导航必须走 shape-only Metal sublayer，Qt widget 不可见，透明四角不得产生任何有色矩形 backing。", "功能正确性", "system", "在问题出现所需的真实 HDR 像素重叠前置条件下验证修复。", "JPEG HDR 窗口、zoom×4、native overlay probe 与 window-scoped screencapture 可用。", "同一右侧 shape layer 的 opacity=0.5、opacity=1.0 与隐藏三帧，按钮 rect 完全位于 image crop。", "核对 surface/Qt visibility/native count；比较 fractional/full 两帧对应中心像素的 RGB 变化，并比较四个精确角 patch 的对应像素变化与外侧局部连续性。", "surface=metal-sublayer、Qt=false、按钮覆盖 HDR；四角局部平均 RGB 不连续≤8；fractional/full 中心 RGB 变化≥5；四角对应像素变化≤8。", "隐藏 shape layers，保留三帧、哈希与 patch 指标。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-THEME-BACKGROUND-STABILITY", "Light Theme 打开 HDR 图片并揭示 Metal 后，视口背景必须保持 #969696，不得约两秒后变浅。", "功能正确性", "system", "以真实屏幕像素验证 Qt→Metal reveal 的背景一致性。", "Light Theme、JPEG、真实 Cocoa Window 与 screencapture 可用。", "主题切换 driver 的 2.4s 前置截图与 pre-dark telemetry。", "在 viewport 外露且避开图像的区域采样中位 RGB，并核对 renderer 诊断。", "telemetry 始终为 (150,150,150)，截图每通道与 150 差≤8。", "保留截图及采样坐标；不修改持久化设置。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-THEME-BACKGROUND-SWITCH", "HDR layer 已显示时切换 Dark Theme，背景必须更新为 #212121。", "功能正确性", "system", "验证原生 layer 不会冻结 AppKit 动态色或忽略应用主题。", "同一 JPEG 窗口和确定性非持久化主题 driver 可用。", "postLoad 后 3.0s 切 Dark；按进程启动时间 4.5s 与 5.2s 截图以覆盖启动/解码抖动。", "检查 test-theme-dark 后 renderer RGB，并在同一外露背景区域取样。", "所有 post-dark telemetry=(33,33,33)，两帧截图每通道与 33 差≤8。", "关闭窗口；不改变 QSettings。", "tests/hdr_quality_system.py"),
    case("SYS-HDR-TIME-BEHAVIOR", "规定工作负载的解码、持久图层几何更新与120Hz compositor probe 必须全部达标。", "时间行为", "system", "聚合验证端到端时间行为。", "M3 Pro/XDR、两类48MP基线各3次及三格式交互。", "6个decode样本、prepared稳态 geometry 样本、三格式 persistent telemetry 与专用 probe。", "按各测量窗口计算 average/P99/max/throughput，并逐项比较固定阈值。", "全部 decode/geometry、persistent handoff、零交互 Metal present 与120 updates/s断言通过，原始样本写入 JSON。", "进程全部终止。", "tests/hdr_quality_system.py"),
]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    required = {
        "id", "atomic_acceptance_criterion", "quality_attribute", "test_level",
        "test_purpose", "preconditions", "input_data", "operation_steps",
        "expected_result", "postconditions", "test_code", "evidence_file",
    }
    identifiers = [item["id"] for item in CASES]
    validation_errors = []
    if len(identifiers) != len(set(identifiers)):
        validation_errors.append("test case identifiers are not unique")
    for item in CASES:
        missing = sorted(required - item.keys())
        empty = sorted(key for key in required if not item.get(key))
        if missing or empty:
            validation_errors.append({"id": item.get("id"), "missing": missing, "empty": empty})
    phase_counts = {
        phase: sum(item["test_level"] == phase for item in CASES)
        for phase in ("static", "unit", "integration", "system")
    }
    record = {
        "schema_version": "1.0",
        "kind": "atomic-test-case-specification",
        "release": "v0.1.4",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "execution_order": ["static", "unit", "integration", "system"],
        "required_case_fields": sorted(required),
        "case_count": len(CASES),
        "phase_counts": phase_counts,
        "cases": CASES,
        "validation_errors": validation_errors,
        "passed": not validation_errors and all(count > 0 for count in phase_counts.values()),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(record, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"case_count": len(CASES), "phase_counts": phase_counts, "passed": record["passed"]}, ensure_ascii=False))
    return 0 if record["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
